pof_username: foo
pof_password: bar
name: Rodney

admin_email: foo@bar.com

topics:
  - name: "Biking"
    interest_matchers:
      - '(?<!motor |motor)bik(e|ing)|cycling'
      - '(bike|cycle) ?touring'
    message: "I see you're into biking. Have you been on any good rides lately? In the last couple of years I've been quite taken with the road riding in the UK."

  - name: "Cooking"
    interest_matchers: ['cook(ing)?']
    message: "I also enjoy an epic session in the kitchen. Have you cooked anything awesome lately? I've recently been obsessing over curry again after stealing some secret techniques from a friend. Yumm!"

  - name: "Game of Thrones"
    interest_matchers: ['game of thrones']
    message: "I also (like everyone it seems) have been following Game of Thrones over the years. That show is pretty addictive, but they should definitely give up and rename it to Game of Porn!"
