development:
  adapter: 'mysql2'
  user: 'root'
  password: 'foobar'
  database: 'turbot_dev'

test:
  adapter: 'mysql2'
  user: 'root'
  password: 'foobar'
  database: 'turbot_test'

prod:
  adapter: 'mysql2'
  user: 'root'
  password: 'foobar'
  database: 'turbot_prod'
